### ISSUE TITLE
Compilation error on FreeBSD 10.2

### ISSUE THREAD

**Issue by jdn06** [baruch/diskscan#45]
I tried to compile on FreeBSD 10.2 with;
- clang version 3.4.1
- python 2.7
- ninja-1.6.0

I had the following error:
```
arch/arch-posix.c:80:6: error: redefinition of 'disk_dev_cdb_in'
void disk_dev_cdb_in(disk_dev_t *dev, unsigned char *cdb, unsigned cdb_len, unsigned char *buf, unsigned buf_size, unsigned *buf_read, unsigned char *sense, unsigned sense_size, unsigned *sense_read, io_result_t *io_res)
     ^
arch/arch-posix.c:73:6: note: previous definition is here
void disk_dev_cdb_in(disk_dev_t *dev, unsigned char *cdb, unsigned cdb_len, unsigned char *buf, unsigned buf_size, unsigned *buf_read, unsigned char *sense, unsigned sense_size, unsigned *sense_read, io_result_t *io_res)
     ^
```
